services:
  mysql:
    image: mysql
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: authchat
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: ./auth-backend
    container_name: auth
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/authchat
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123

  frontend:
    build: ./main-app-frontend
    ports:
      - "4200:4200"
  chat-ai:
    build: ./ai-chatbot-backend
    ports:
      - "5000:5000"
  front-next:
    build: ./chatbot-frontend
    ports:
      - "3000:3000"

volumes:
  mysql_data:
